RosLibRust/roslibrust

roslibrust/test_msgs/msg/Constants.msg
roslibrust/test_msgs/msg/NodeInfo.msg
roslibrust_codegen/src/lib.rs
roslibrust_test/src/lib.rs
roslibrust_test/src/main.rs

Add example for parsing tests and fix the tokenization

---

CHANGELOG.md
Cargo.lock
README.md
roslibrust/src/comm.rs
roslibrust/src/integration_tests.rs
roslibrust/src/lib.rs
roslibrust_codegen/Cargo.toml
roslibrust_codegen/src/lib.rs
roslibrust_codegen/src/parse.rs
roslibrust_test/Cargo.toml
roslibrust_test/src/lib.rs
roslibrust_test/src/main.rs

Adds the ability to run a service server.
This is pretty basic so far and pretty minimally tested, needs more work but should be a good start

Support service server

---

CHANGELOG.md
roslibrust/local_msgs/std_msgs/msg/DurationI.msg
roslibrust/local_msgs/std_msgs/msg/TimeI.msg
roslibrust/src/integral_types.rs
roslibrust/src/lib.rs
roslibrust_codegen/src/parse.rs
roslibrust_test/src/lib.rs

Integral types for time duration

---

roslibrust/src/codegen/mod.rs
roslibrust_test/src/lib.rs

Escape all variable names rather than trying to check if they're keywords

---

roslibrust/Cargo.toml
roslibrust/src/lib.rs
roslibrust/src/rosapi/mod.rs
roslibrust/src/rosapi/types.rs
roslibrust/src/rosbridge/integration_tests.rs
roslibrust/src/rosbridge/mod.rs

I don't love how types.rs works, but otherwise happy with this.
My plan is to re-org per #62 and then clean this up, but do want to merge this now.

Working support for rosapi

---

CHANGELOG.md
roslibrust_codegen/src/parse.rs
roslibrust_codegen/src/utils.rs
roslibrust_test/src/main.rs
roslibrust_test/src/ros2.rs

Fix char bug (again), parse package name from xml

---

CHANGELOG.md
Cargo.lock
roslibrust/src/lib.rs
roslibrust_codegen/src/lib.rs
roslibrust_codegen/src/utils.rs
roslibrust_test/Cargo.toml
roslibrust_test/src/main.rs

Makes it possible to generate useful logs during code generation if using the runtime method. Logs look like this: 
```
ssnover:roslibrust$ RUST_LOG=debug cargo run --bin roslibrust_test
Blocking waiting for file lock on build directory
Compiling roslibrust v0.6.0 (/home/ssnover/dev/roslibrust/roslibrust)
Compiling roslibrust_test v0.1.0 (/home/ssnover/dev/roslibrust/roslibrust_test)
Finished dev [unoptimized + debuginfo] target(s) in 5.50s
Running `target/debug/roslibrust_test`
[2023-02-04T18:46:14Z WARN  roslibrust_codegen::utils] No ROS_PACKAGE_PATH defined.
[2023-02-04T18:46:14Z DEBUG roslibrust_codegen] Codegen is looking in following paths for files: ["/home/ssnover/dev/roslibrust/assets/ros1_common_interfaces", "/home/ssnover/dev/roslibrust/assets/ros1_test_msgs", …
```

Add more logging and proactive detection of possible issues to logs

---

roslibrust/src/ros1/node.rs
roslibrust/tests/ros1_xmlrpc.rs
roslibrust_codegen_macro/src/lib.rs

Enable multiple publishers on a single topic, guarded on same topic type str

---

roslibrust/examples/ros1_listener.rs
roslibrust/src/ros1/master_client.rs
roslibrust/src/ros1/mod.rs
roslibrust/src/ros1/node.rs
roslibrust/src/ros1/publisher.rs
roslibrust/src/ros1/subscriber.rs
roslibrust/src/ros1/tcpros.rs
roslibrust/tests/ros1_xmlrpc.rs

Native subscribers are now supported!

---

roslibrust_codegen/src/lib.rs

Closes: https://github.com/Carter12s/roslibrust/issues/124

Added defaults to MD5SUM and DEFINITION

---

.github/workflows/galactic.yml
.github/workflows/humble.yml
.github/workflows/noetic.yml
README.md
roslibrust/src/rosbridge/client.rs

Fix build on 1 72

---

Cargo.lock
roslibrust_genmsg/Cargo.toml
roslibrust_genmsg/src/helpers.rs

Increasing gen message dependencies

---

CHANGELOG.md
roslibrust/examples/ros1_service_client.rs
roslibrust/examples/ros1_service_server.rs
roslibrust/src/ros1/service_client.rs
roslibrust/src/ros1/service_server.rs

Service servers now default to a persistent behavior and will respond to multiple request bodies on the same TCP stream.
Closes: #162

Persistent service clients

---

roslibrust/src/ros1/service_client.rs
roslibrust/src/ros1/service_server.rs

Cleaning up error handling for ROS1 services and giving them some sane error types
Closes: #164

Add proper error handling for Ros1 Services

---

roslibrust/src/ros1/node/actor.rs
roslibrust/src/ros1/service_server.rs
roslibrust/src/ros1/tcpros.rs

Connection header for ros1 service servers now provides correct fields so that it works with `rosservice` cli
Closes: #161

Fix service servers with rosservice

---

roslibrust_codegen/tests/package_search.rs

test broken by catkin ignore, was a low value test

---

CHANGELOG.md
roslibrust/examples/ros1_talker.rs
roslibrust/src/ros1/master_client.rs
roslibrust/src/ros1/node/actor.rs
roslibrust/src/ros1/node/handle.rs
roslibrust/src/ros1/publisher.rs
roslibrust/src/ros1/subscriber.rs
roslibrust/tests/ros1_xmlrpc.rs

- Plumbed through the latching behavior for ROS1 native publishers
- Cleaned up the internal code structure of Publication
- Fixed a few warnings we'd been ignoring for a while
- Added integration tests to confirm latching behavior for publishers is good
Closes: #182

Add latching behavior to native publishers

---

docker/galactic/Dockerfile
docker/humble/Dockerfile

Added some additional deps to ci images around pkg-config and libssl-dev

---

CHANGELOG.md
roslibrust_common/src/traits.rs

Fix server server not being send

---

roslibrust_codegen/src/gen.rs
roslibrust_test/src/ros1.rs
roslibrust_test/src/ros2.rs

Re-hide dead_code in messages
