RosLibRust/roslibrust

src/message_gen.rs
=> Fix generating empty impls when message has no associated constants

roslibrust_rospack/src/lib.rs
This was a pretty dumb oversight, but many files don't have an extension and will return `None`. I've updated the parsing to account for this.
=> Don't unwrap on checking for extension

CHANGELOG.md, roslibrust_codegen/src/lib.rs
Per title.
I also refactored so that areas where a `BTreeMap<String, MessageFile>` was being returned will just return a `Vec<MessageFile>` now which means we don't have document the format of that `String`.
This will allow other possible code generation backends to be written; perhaps C++ and/or Typescript to throw two completely meaningless and randomly chosen examples out there.
=> Split codegen into two public functions with the option to call them separately

roslibrust_codegen/src/lib.rs, roslibrust_codegen/src/utils.rs
Teeny tiny.
Also refactored `parse_ros_package_info` to log an error, return a `Result` and continue in the event of an invalid `package.xml`. On the off chance there's an additional file of that name hanging around on disk it won't mess with the user.
Fixes #23
=> Replace prints to stderr with log warn and error macros

CHANGELOG.md, roslibrust_codegen/src/gen.rs, roslibrust_codegen/src/lib.rs, roslibrust_codegen/src/parse.rs
Split our parsing up in order to represent the concept of a `ParsedMessageFile` vs a `MessageFile` such that the prior can be made before dependency resolution and the latter can eventually be made to hold more information that requires a resolved dependency graph.
I also made several clean ups around panics and split things into new functions. These could be tested individually if one was so inclined.
In my next PR, I'll be utilizing the new `MessageFile` struct to hold onto a few pieces of data including: `md5sum`, `has_header`, `is_fixed_size`, `is_message`, etc. which are things we'll need for ROS1 native and some incoming C++ code generation I'm working on.
=> Refactor the pipeline for parsing ROS messages and services ahead of adding md5sum

.github/workflows/noetic.yml, CHANGELOG.md, roslibrust/examples/ros1_ros2_bridge_example.rs, roslibrust/src/lib.rs, roslibrust_codegen/Cargo.toml, roslibrust_codegen/src/gen.rs, roslibrust_codegen/src/integral_types.rs, roslibrust_codegen/src/lib.rs, roslibrust_codegen/src/parse.rs, roslibrust_codegen/src/utils.rs, roslibrust_codegen_macro/src/lib.rs, roslibrust_test/src/main.rs
* Added calculation of md5sum. Checked a handful against generated header files, specifically `Image.msg` which includes an array and a Header and `TransformStamped.msg` which includes a Header and another msg datatype from the same package.
* Added helper methods throughout to make structs a little smarter and reduce duplicated code
* Adjusted pipeline to exclusively use ROS types and data directly derived from msg file during parsing and to not do any Rust code generation until we are doing generation (specifically around literals for constants).
=> Generate md5sum

Cargo.lock, Cargo.toml, roslibrust_codegen/src/gen.rs, roslibrust_codegen/src/lib.rs, roslibrust_codegen/src/parse.rs, roslibrust_codegen/src/utils.rs, roslibrust_gencpp/Cargo.toml, roslibrust_gencpp/assets/msg.h.j2, roslibrust_gencpp/src/helpers.rs, roslibrust_gencpp/src/lib.rs, roslibrust_gencpp/src/main.rs, roslibrust_gencpp/src/spec.rs
Currently missing support for constants. We have some peculiarities with our message generation which means it doesn't quite work like the official genmsg/gencpp tools yet (namely, it's not possible to call this without includes as that's how we find the file and returned the parsed version).
Can be invoked with
```
cargo run --bin gencpp -- -m assets/ros1_common_interfaces/std_msgs/msg/ColorRGBA.msg \
-p std_msgs \
-o /tmp/ColorRGBA.h \
-Istd_msgs:assets/ros1_common_interfaces/std_msgs
```
This does not currently support services or constants. But I prefer to keep PRs small so I think those can come in later PRs. I think those should be included at a minimum before we publish the crate. I've also made public a whole lot of our parsed structures from `roslibrust_codegen`. Those are going …
=> Rough first pass on generation of C++ header files for messages

Cargo.lock, roslibrust_codegen/src/gen.rs, roslibrust_codegen/src/integral_types.rs, roslibrust_codegen/src/lib.rs, roslibrust_codegen/src/parse.rs, roslibrust_test/src/ros1.rs, roslibrust_test/src/ros2.rs, roslibrust_test/tests/ros1_codegen_tests.rs
I have no idea if this valid or not for ROS2, but our code generation currently has no way to discern or behave differently (and when generating a module this means ROS1 and ROS2 types could easily be mixed...).
=> Add md5sum as associated constant to RosMessageType and RosServiceType

roslibrust_gencpp/src/lib.rs, roslibrust_gencpp/src/main.rs
Immediately when trying to use the library version ran into the issue that there's a lot of work being done every time the `generate_X` functions are called so it'd be nice to only do that work once.
=> Allow the API to generate multiple messages so that clients doing so don't need to rebuild the entire dependency graph every single time

roslibrust_genmsg/src/cpp.rs, roslibrust_genmsg/src/spec.rs, roslibrust_genmsg/test_package/include/sensor_msgs/BatteryState.h, roslibrust_genmsg/test_package/include/std_msgs/Header.h, roslibrust_genmsg/test_package/include/std_srvs/TriggerResponse.h
* Updated the mapping for string type in C++ to exactly what ROS uses in order to allow overriding the allocator.
* Added forgotten `uint64` to list of ROS types.
=> Add uint64 to ros type list and replace C++ mapping for string

roslibrust_genmsg/src/helpers.rs, roslibrust_genmsg/src/lib.rs, roslibrust_genmsg/src/main.rs
Figured out this API and it's pretty handy for some upcoming generation replacing some empy code with a ton of helpers.
=> Add the ability to pass custom minijinja filters to the code generator

roslibrust_codegen/src/gen.rs, roslibrust_codegen/src/lib.rs, roslibrust_codegen/src/parse/mod.rs, roslibrust_genmsg/assets/msg.h.j2, roslibrust_genmsg/regenerate-test-msgs.sh, roslibrust_genmsg/src/helpers.rs, roslibrust_genmsg/src/spec.rs, roslibrust_genmsg/test_package/include/geometry_msgs/Point32.h, roslibrust_genmsg/test_package/include/geometry_msgs/Polygon.h, roslibrust_genmsg/test_package/include/sensor_msgs/BatteryState.h, roslibrust_genmsg/test_package/include/sensor_msgs/CameraInfo.h, roslibrust_genmsg/test_package/include/std_msgs/Char.h, roslibrust_genmsg/test_package/include/std_msgs/Header.h, roslibrust_genmsg/test_package/include/std_srvs/TriggerRequest.h, roslibrust_genmsg/test_package/include/std_srvs/TriggerResponse.h, roslibrust_genmsg/test_package/include/test_package/Test.h, roslibrust_genmsg/test_package/src/test_main.cpp, roslibrust_test/src/ros1.rs, roslibrust_test/src/ros2.rs
This MR introduces support for parsing fixed-size arrays and carrying their metadata around to the code generators. There's still a little support required in order to support fixed-size arrays in Rust code due to a lack of support in `serde`, however there is a possible workaround that I will investigate in a follow-up MR: https://github.com/serde-rs/serde/issues/631#issuecomment-322677033
The impetus for this was incorrect code generation for `sensor_msgs/CameraInfo` which has a relatively complex definition. As a result, I've added it to the `test_package` for C++. In order to detect regressions in checksum (and therefore parsing), I augmented some of the `ros::message_traits` structs/functions to use `constexpr` which allows checking the value in a `static_assert`. This should be …
=> Update parsing to support fixed-size arrays in ROS1

.github/workflows/noetic.yml, Cargo.lock, roslibrust/Cargo.toml, roslibrust/examples/native_ros1.rs, roslibrust/src/ros1/master_client.rs, roslibrust/src/ros1/node_server.rs, roslibrust/src/rosapi/mod.rs, roslibrust/src/rosbridge/integration_tests.rs, roslibrust/src/rosbridge/topic_provider.rs
Rolls out test_log usage to core roslibrust crate.
Fixes that we weren't testing with all features in CI (Major TODO to test matrix of features)
Fixes many warnings (but not all, because quite a few are legit)
=> Improve test logging, fix a variety of compiler warnings

roslibrust_codegen/src/gen.rs, roslibrust_codegen/src/integral_types.rs, roslibrust_codegen/src/lib.rs, roslibrust_test/src/ros1.rs, roslibrust_test/src/ros2.rs
Follow up to my PR from this morning which also adds the message definition to the Rust trait `RosMessageType` as this info is necessary in ROS1 native implementation.
=> Add definition to RosMessageType trait and generate Rust source to include it

Cargo.lock, roslibrust/Cargo.toml, roslibrust/examples/native_ros1.rs, roslibrust/examples/ros1_talker.rs, roslibrust/src/ros1/master_client.rs, roslibrust/src/ros1/mod.rs, roslibrust/src/ros1/node.rs, roslibrust/src/ros1/publisher.rs, roslibrust/src/ros1/tcpros.rs, roslibrust/src/ros1/xmlrpc_server.rs, roslibrust/tests/ros1_xmlrpc.rs, roslibrust_codegen/src/lib.rs
Alright! So this has numerous issues; it will explode if you look at it wrong, but I successfully got the `ros1_talker` example to publish data to the listener node from the ROS1 tutorial: https://github.com/ros/ros_tutorials/blob/noetic-devel/rospy_tutorials/001_talker_listener/listener.py
Output from the listener node
```
demo_nodes-talker_listener-1  | [INFO] [1693161083.219396]: /listenerI heard hello world from rust 322
demo_nodes-talker_listener-1  | [INFO] [1693161084.220899]: /listenerI heard hello world from rust 323
demo_nodes-talker_listener-1  | [INFO] [1693161085.222399]: /listenerI heard hello world from rust 324
demo_nodes-talker_listener-1  | [INFO] [1693161086.227722]: /listenerI heard hello world from rust 325
demo_nodes-talker_listener-1  | [INFO] [1693161087.228721]: …
```
=> ROS1 Native publishing first pass

Cargo.lock, roslibrust/Cargo.toml, roslibrust/src/ros1/mod.rs, roslibrust/src/ros1/names.rs, roslibrust/src/ros1/node.rs
Add a submodule for managing logic around graph name validation and resolution.
Pulled the tests from the ROS docs: http://wiki.ros.org/Names
=> Add a submodule for managing logic around graph name validation and resolution

.github/workflows/galactic.yml, .github/workflows/humble.yml, .github/workflows/noetic.yml, .github/workflows/noetic_gencpp.yml
This is a first step to mitigating the integration test hung jobs, I browsed through our actions and approximately doubled the max time I saw for passing, healthy jobs. The default appears to be 6 hours.
=> Add timeouts on a per-job basis to each workflow config

roslibrust/src/rosbridge/integration_tests.rs, roslibrust/tests/ros1_xmlrpc.rs
Closes: https://github.com/Carter12s/roslibrust/issues/122
Also nudged some other timeouts up. Just trying to keep CI jobs from hanging for 20 minutes.
Doesn't actually solve root problem likely, but makes failure quicker / more obvious (hopefully with better logs too).
=> Add timeouts to ros1 tests

Cargo.lock, roslibrust_codegen/Cargo.toml, roslibrust_codegen/src/gen.rs, roslibrust_codegen/src/lib.rs, roslibrust_codegen/src/parse/action.rs, roslibrust_codegen/src/parse/mod.rs, roslibrust_codegen/src/parse/msg.rs, roslibrust_codegen/src/parse/srv.rs, roslibrust_codegen_macro/src/lib.rs, roslibrust_genmsg/src/lib.rs, roslibrust_test/src/main.rs
Closes: https://github.com/Carter12s/roslibrust/issues/126
Closes: https://github.com/Carter12s/roslibrust/issues/128
Trying to catch some common user errors and make them more clear. Investigated automated tests for these kinds of errors, but it looks like it is actually pretty annoying to setup. Looks like this will do the job, but a little much to setup right now: https://crates.io/crates/compiletest_rs
These test checks were manually performed by me while setting this up:
Manually modifying calling_services to introduce a typo on this line:
`roslibrust_codegen_macro::find_and_generate_ros_messages!("assets/ros1_common_interfacs",);`
Now produces the following compilation error when invoking `cargo run --example calling_service`
```
error: Failed to find any services or messages while …
```
=> Better errors from codegen

CHANGELOG.md, example_package/build.rs, roslibrust_codegen/src/lib.rs, roslibrust_codegen_macro/src/lib.rs, roslibrust_genmsg/src/lib.rs, roslibrust_test/src/main.rs
See changelog.
Issue Number: None (just went for it)
=> Abilty to correctly inform cargo of file dependnencies in build.rs

.github/workflows/iron.yml, README.md, docker/galactic/Dockerfile, docker/humble/README.md, docker/iron/Dockerfile, docker/iron/README.md, docker/iron/entrypoint.sh, docker/iron_compose.yaml, docker/noetic/Dockerfile, docker/noetic_cpp/Dockerfile
Adds CI support for testing with Iron
Issue Number: #137 
- N/A Update CHANGELOG.md
=> Add iron CI

CHANGELOG.md, roslibrust/examples/native_ros1.rs, roslibrust/examples/ros1_listener.rs, roslibrust/examples/ros1_talker.rs, roslibrust/src/lib.rs, roslibrust/src/ros1/master_client.rs, roslibrust/src/ros1/mod.rs, roslibrust/src/ros1/names.rs, roslibrust/src/ros1/node/actor.rs, roslibrust/src/ros1/node/handle.rs, roslibrust/src/ros1/node/mod.rs, roslibrust/src/ros1/node/xmlrpc.rs, roslibrust/src/ros1/publisher.rs, roslibrust/src/ros1/subscriber.rs, roslibrust/src/rosbridge/mod.rs, roslibrust/tests/ros1_xmlrpc.rs
Reorganize the code in node.rs into a couple separate files with different areas of concern to manage growing number of node actor methods.
As I was starting in on implementation of native Service Clients I was finding the code here growing in difficulty to navigate `node.rs` so I split it:
* `mod.rs` is for helpers and utilities
* `actor.rs` is where most of the node administration lives for the `NodeServer` actor
* `handle.rs` is for the struct that user code uses as a handle
* `xmlrpc.rs` has the former `xmlrpc_server.rs` module since a lot of that code was tied to code in `node.rs` which became clear as I was fixing `use` statements.
N/A
=> Reorganize the code in node.rs into a couple separate files

CHANGELOG.md, Cargo.lock, roslibrust/Cargo.toml, roslibrust_codegen/src/gen.rs, roslibrust_codegen/src/lib.rs, roslibrust_codegen/src/parse/mod.rs, roslibrust_test/Cargo.toml, roslibrust_test/src/ros1.rs, roslibrust_test/src/ros2.rs, roslibrust_test/tests/ros1_codegen_tests.rs, roslibrust_test/tests/ros2_codegen_tests.rs
ROS1 serialization with serde_rosmsg requires that fixed sized arrays be represented not as Vec<_> but as [_; N]. The two are sent over the wire differently. Most of the support for this was already plumbed through, so this just closed the loop at the end, but is hitting the "const generic" barrier.
Closes: #148
=> Support for Fixed Sized Arrays

CHANGELOG.md, roslibrust_codegen/src/lib.rs, roslibrust_codegen/src/utils.rs
Make additional public APIs available. Use case is when consuming interface libraries using an external non-ROS build-system. `package.xml` is not available, so I need to provide the package paths manually.
=> Flexible public codegen APIs

CHANGELOG.md, roslibrust/src/ros1/publisher.rs
Prior to this change running `rostopic hz` with any ros1 native publisher would result in no messages being received. This was due to "*" being sent as the md5sum for the topic (which appears undocumented). I suspect this was the behavior for all generic subscriptions (at least with rospy). With this change in place `rostopic hz` now works.
=> Debugging rostopic hz

docker/noetic_compose.yaml, roslibrust/src/ros1/node/actor.rs, roslibrust/src/ros1/node/handle.rs, roslibrust/src/ros1/publisher.rs, roslibrust/src/ros1/service_client.rs, roslibrust/src/ros1/service_server.rs, roslibrust/src/ros1/tcpros.rs, roslibrust/src/rosbridge/client.rs, roslibrust/src/rosbridge/mod.rs
Add logic to both ServiceClient and ServiceServer to correctly clean-up after themselves when their respective handles are dropped.
Closes: #165
=> Fix Service Servers Shutdown Cleanly

CHANGELOG.md, Cargo.lock, roslibrust/src/ros1/publisher.rs, roslibrust/src/ros1/service_server.rs, roslibrust/src/ros1/subscriber.rs, roslibrust/src/ros1/tcpros.rs, roslibrust_genmsg/Cargo.toml
Create a common function for receiving a ros1 native connection header, and use it across the 4 receivers (publisher, subscriber, service_client, service_server). Fixes bug where publisher was trying to parse connection header with the overall header length still at the front.
Closes: #171
=> Fix a lot of header shenanigans

CHANGELOG.md, roslibrust/src/ros1/publisher.rs, roslibrust/src/ros1/service_client.rs, roslibrust/src/ros1/service_server.rs, roslibrust/src/ros1/subscriber.rs, roslibrust/src/ros1/tcpros.rs
- Fixed bug where subscribers weren't handling message size correctly
- Standardized logic for receiving a ROS1 message body that was duplicated in subscriber, service_client and service_server
- Added a unit test for subscribers for large payload
Closes: #178
=> Fix 178 subscriber buffer size

.github/workflows/galactic.yml, .github/workflows/humble.yml, .github/workflows/noetic.yml, Cargo.lock, roslibrust/Cargo.toml
This is slightly funky...
I found the repo unable to compile with [dev-dependencies] on one of my machines after updating to last stable rust (1.80).
Root cause turned out to be our lock file pointing at older version time crate, issue may be due to wsl2 host environment, but regardless good to update some stuff.
=> Run Cargo update and update simple logger version

roslibrust/src/lib.rs, roslibrust/src/ros1/mod.rs, roslibrust/src/ros1/node/actor.rs, roslibrust/src/ros1/node/handle.rs, roslibrust/src/ros1/service_server.rs, roslibrust/src/rosbridge/client.rs
=> Use type aliases to clean-up a lot of function definitions

.github/workflows/noetic.yml, CHANGELOG.md, roslibrust/Cargo.toml, roslibrust/src/ros1/node/actor.rs, roslibrust/src/ros1/node/handle.rs, roslibrust/src/ros1/node/mod.rs, roslibrust/src/ros1/node/xmlrpc.rs, roslibrust/src/ros1/publisher.rs, roslibrust/tests/ros1_native_integration_tests.rs
- Dropping the last publisher for a given topic results in publication being cleaned up and unadvertise being called
- Sub various minor cleanups throughout ros1
Closes: #112
=> ROS1 publishers call unadvertise on drop

CHANGELOG.md, roslibrust/src/ros1/node/handle.rs, roslibrust/src/ros1/subscriber.rs, roslibrust/tests/ros1_native_integration_tests.rs, roslibrust_codegen/src/integral_types.rs
Subscribe to a topic without needing to know the type, and then get the received message as a raw vector of bytes, similar to rospy AnyMsg and roscpp ShapeShifter.
This isn't quite what was suggested in https://github.com/Carter12s/roslibrust/issues/190#issuecomment-2276521772-  I couldn't figure out how to make a function within the existing Subscriber that can do different things depending on type, it needs specialization?  Is having both a Subscriber and SubscriberAny bad for other parts of roslibrust?
Closes: #190
- [ :heavy_check_mark: ] Update CHANGELOG.md
=> subscribe to any topic of any type and get received messages as a raw vector of bytes

CHANGELOG.md, Cargo.lock, roslibrust/src/ros1/publisher.rs, roslibrust/src/ros1/subscriber.rs, roslibrust/src/ros1/tcpros.rs, roslibrust_test/Cargo.toml, roslibrust_test/src/performance_ramp.rs
Discovered some bugs in production related to very large messages. Turnout out our usage of write() vs. write_all() on the publisher side was incorrect and would truncate large messages (had to be several MB before I actually saw this occur). With this change messages would send reliably with no upper limit I could find (probably u32 size at this point).
Closes: NAN
=> Change to using write_all

CHANGELOG.md, Cargo.lock, docker/noetic_compose.yaml, roslibrust/Cargo.toml, roslibrust/src/ros1/node/actor.rs, roslibrust/src/ros1/publisher.rs, roslibrust/src/ros1/service_client.rs, roslibrust/src/ros1/service_server.rs, roslibrust/src/ros1/subscriber.rs, roslibrust/src/ros1/tcpros.rs, roslibrust_codegen/Cargo.toml, roslibrust_codegen/src/gen.rs, roslibrust_codegen/src/lib.rs, roslibrust_test/Cargo.toml, roslibrust_test/benches/image_bench.rs, roslibrust_test/src/ros1.rs, roslibrust_test/src/ros2.rs
- Discovered that serde_rosmsg was quite slow on uint8[] -> Vec<u8> deserialization
- Figured out how to make it MUCH faster: https://github.com/adnanademovic/serde_rosmsg/pull/5
- Switched to our own fork of serde_rosmsg to enable to optimization
- Updated codegen to generate types that take advantage of optimization via serde_bytes
- Added criterion based benchmarking to validate speedup (and to start adding performance testing in general):
This resulted in a 71% speedup on sending 1080p color images, from 22ms to 6.3ms.
```
Running benches/image_bench.rs (target/release/deps/image_bench-3e2fda80b1f23a8a)
Gnuplot not found, using plotters backend
image_bench             time:   [6.2894 ms 6.3457 ms 6.4039 ms]
change: [-71.261% -71.004% -70.693%] (p = 0.00 < 0.05)
Performance has …
```
=> Switch to fork of serde_rosmsg

CHANGELOG.md, roslibrust_codegen/src/gen.rs, roslibrust_test/README.md, roslibrust_test/src/ros1.rs, roslibrust_test/src/ros2.rs
Suppresses some warnings in generated code where constants or structs were flagged as unused.
=> Maybe unused

CHANGELOG.md, roslibrust/src/ros1/tcpros.rs
=> Ignore request_type and response_type in header parsing

CHANGELOG.md, roslibrust_codegen/src/integral_types.rs
=> Time conversions

CHANGELOG.md, roslibrust/src/ros1/master_client.rs, roslibrust/src/ros1/node/actor.rs, roslibrust/src/ros1/node/handle.rs, roslibrust/src/ros1/publisher.rs, roslibrust/tests/ros1_native_integration_tests.rs
ROS1 Node Clears any and all Advertises, Subscribes, and Services with the ROS master when dropped. Goal here is that we don't leave junk in `rosnode list` / `rosnode info` after our node shuts down.
I don't love this design and it should be redundant if Publishers / Subscriptions and Service Servers cleanup after themselves correctly, but there is some good redundancy in doing this.
=> Better node cleanup

roslibrust/src/ros1/node/actor.rs, roslibrust/src/ros1/node/handle.rs, roslibrust/src/ros1/publisher.rs
Re-working publisher to use tokio::broadcast as the underlying channel so that one lagging TCP Socket doesn't result in the publisher blocking.
Closes: #206
=> Working publisher using broadcast

CHANGELOG.md, roslibrust/src/ros1/publisher.rs, roslibrust/src/ros1/service_client.rs, roslibrust/src/ros1/service_server.rs, roslibrust/src/ros1/subscriber.rs, roslibrust/src/ros1/tcpros.rs
While interacting with zenoh-ros1-bridge I discovered that their implementation or ROS1 service clients (rosrust based) didn't "complete" a service request until the underlying TCP socket shutdown. They relied on a service server closing the TCP socket after the request is completed if the persistent flag was not set in the header. I don't love that they are doing that and filed an issue over there, but we should improve our support for the persistent flag regardless.
https://github.com/eclipse-zenoh/zenoh-plugin-ros1/issues/212
- Closes #210
=> ROS1 Services support persistent

CHANGELOG.md, Cargo.lock, Cargo.toml, roslibrust_ros1/Cargo.toml, roslibrust_test/Cargo.toml
25% gain in image_bench:
```
Running benches/image_bench.rs (/home/carter/open_source/roslibrust/target/release/deps/image_bench-53c844cf7ef286e4)
Gnuplot not found, using plotters backend
image_bench             time:   [16.460 ms 16.821 ms 17.188 ms]
change: [-28.889% -26.797% -24.635%] (p = 0.00 < 0.05)
Performance has improved.
```
=> Update roslibrust_serde_rosmsg to improve serialization speed

CHANGELOG.md, example_package/src/main.rs, example_package_macro/src/main.rs, roslibrust/examples/generic_client.rs, roslibrust/examples/generic_client_services.rs, roslibrust/examples/generic_message.rs, roslibrust_common/src/lib.rs, roslibrust_common/src/traits.rs, roslibrust_mock/src/lib.rs, roslibrust_ros1/src/lib.rs, roslibrust_rosbridge/src/lib.rs, roslibrust_zenoh/src/lib.rs
Adds a better generic handle for working with Ros in general
=> Node generics

CHANGELOG.md, Cargo.lock, Cargo.toml, roslibrust/Cargo.toml, roslibrust/examples/ros1_async_service_server.rs, roslibrust_codegen/Cargo.toml, roslibrust_common/src/traits.rs, roslibrust_mock/src/lib.rs, roslibrust_ros1/Cargo.toml, roslibrust_ros1/src/main.rs, roslibrust_ros1/src/service_server.rs, roslibrust_rosapi/Cargo.toml, roslibrust_rosbridge/Cargo.toml, roslibrust_rosbridge/src/client.rs, roslibrust_rosbridge/src/lib.rs, roslibrust_test/Cargo.toml, roslibrust_test/tests/ros1_blocking_service_async.rs, roslibrust_zenoh/src/lib.rs
- Changes all back-ends to always call user provided service functions inside of `spawn_blocking`
- Adds example showing how to perform async operations inside of a service handle
- Adds integration test confirming this behavior for ros1
Closes: #108
=> Async Service Examples and Backend Fixes

CHANGELOG.md, assets/ros1_test_msgs/msg/ADSBVehicle.msg, roslibrust_codegen/src/gen.rs, roslibrust_test/src/ros1.rs, roslibrust_test/src/ros2.rs
Messages like https://github.com/mavlink/mavros/blob/master/mavros_msgs/msg/ADSBVehicle.msg fail to build as described in #229 without this raw string literal change- I've added a copy of it into `ros1_test_msgs/`.
Closes: #229
=> add more hashes to raw string literal to avoid unusual ros message definition comment problems

Cargo.lock, roslibrust_common/Cargo.toml, roslibrust_common/src/traits.rs
Just purging a dep that should never has been used, std::future::Future has been in std since 1.36.
=> Remove unneeded dep on futures::Future from _common

CHANGELOG.md, Cargo.lock, roslibrust/Cargo.toml, roslibrust/examples/tokio_stream_operations.rs, roslibrust_common/Cargo.toml, roslibrust_common/src/traits.rs, roslibrust_genmsg/src/lib.rs
Futures stream support.
Closes: #240
=> Subscribers Now Support futures_core::Stream via .to_stream() + Example

.github/workflows/noetic.yml, CHANGELOG.md, roslibrust/examples/generic_client_services.rs, roslibrust/examples/rosbridge_service_server.rs, roslibrust/tests/ros1_native_integration_tests.rs, roslibrust_common/src/lib.rs, roslibrust_rosbridge/src/integration_tests.rs, roslibrust_test/Cargo.toml, roslibrust_test/tests/mock_node_is_send.rs
Changes ServiceFn error type to anyhow::Error. This was the only effective way I found to work around significant lifetime issues where Rust would get confused about whether a given closure/future was Box<dyn Error + Send + Sync> or Box<dyn Error + Send + Sync + 'static>.
Closes: #262
=> Solve complex lifetime issue with ServiceFn
